### PR TITLE
[breaking change] Update retain to use &mut instead of &

### PR DESCRIPTION
**Pull request by Xaeroxe**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-smallvec/61)

### CODE REVIEW

**Comment by Xaeroxe** [comment]
cc @mbrubeck

**Comment by mbrubeck** [comment]
Since this is a breaking change, we might want to consider if there are any other breaking changes we'd like to make, so that we can release them all together as smallvec 1.0.0.

**Comment by Xaeroxe** [comment]
@mbrubeck well it's been almost 3 months and we haven't gotten any response on that.  Do we just want to go ahead and merge it?

**Comment by mbrubeck** [comment]
@bors-servo r+

Yeah, sorry. I should have included this in the recent 0.5.0 release, but I forgot.  It can go in the next version.

**Pull request merged**
