### PR TITLE
Version 1.11.0

### PR DESCRIPTION
**Pull request by mbrubeck**

### CODE REVIEW

**Review by jdm — APPROVED** [review]

**Comment by mbrubeck** [comment]
Notable changes include #292 and #298.  Some additional eyes on those changes might be good before we release this.

After this is released, I'd like to make #284 the main branch, and begin preparing for smallvec 2.0.

**Review by Manishearth — APPROVED** [review]
r=me for the version bump, haven't looked too closely at the other changes

**Comment by the8472** [comment]
Note that DrainFilter in std has been replaced with [ExtractIf](https://doc.rust-lang.org/nightly/std/vec/struct.ExtractIf.html) which doesn't keep draining on drop.

**Comment by mbrubeck** [comment]
> Note that DrainFilter in std has been replaced with [ExtractIf](https://doc.rust-lang.org/nightly/std/vec/struct.ExtractIf.html) which doesn't keep draining on drop.

Thanks for the heads-up.  We can add this new API behind a separate feature if someone has time to implement it, and we can drop the old API in version 2.0.

**Pull request merged**
