### PR TITLE
ci: Fix running fuzz on `v2` branch.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
Running the `fuzz` step wasn't happening, so this is an attempt at fixing that.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
This now appears to be actually failing, not just a CI configuration issue.

**Review by mbrubeck — APPROVED** [review]

**Comment by waywardmonkeys** [comment]
@mbrubeck While I have the time to fix CI, I don't have the time to debug and figure out why the fuzz is actually failing on `v2`. :(

**Comment by mbrubeck** [comment]
That's fine.  We can leave this open until we can fix the underlying issue.

**Comment by mbrubeck** [comment]
resolved by #332

**Pull request closed without merging**
