### PR TITLE
Add simple fuzzing

### PR DESCRIPTION
**Pull request by dpc**
Add simple fuzzing
    
Add infrastructure to automatically run fuzzers in CI,
and implement a simple fuzzing test based on triggering all (most)
public APIs in a randimized way.
    
As far as I was able to try, it catches the previous unsoundness issues
in a matter of seconds. This can be tried by changing the `path = "../"` dependency to
`version = "=0.6.3"` etc. and running the fuzzer manually. (Note: You'll need
to tweak the `Cargo.lock` to allow downloading the yanked versions).

### CODE REVIEW

**Comment by dpc** [comment]
It will probably take me couple of iterations to figure out the details and do some final polishing, but feel free to give feedback.

**Comment by dpc** [comment]
I can rebase if someone reviews. :D

**Comment by mbrubeck** [comment]
Running the fuzzer returns an error unless I create an `in` directory and add some input files first. Should there be initial input files checked in to the repository?

**Comment by dpc** [comment]
@mbrubeck Are you using afl? Yes. Please do something like:

```
mkdir in
echo "a" > in/foo
```

**Comment by dpc** [comment]
I'm not sure if I should add this to the `README.md` or just check it in. Ideally `in` should contain some failing cases, as far as I understand, though it i not necessary for such a simple fuzzing target.

**Comment by mbrubeck** [comment]
Yes, having a basic one-byte input checked in to the repo would be good; it'll be one less step for people to get started (or for scripts running fuzzing in CI).

**Comment by mbrubeck** [comment]
The build failure is because #145 changed the API for `SmallVec::drain`.  It takes a range argument now.

**Comment by dpc** [comment]
@mbrubeck Oh. I did a naive rebase, as I don't have access to my normal dev box. I'll fix it later today / tomorrow. Thanks!

**Comment by dpc** [comment]
@mbrubeck Done. :)

**Comment by mbrubeck** [comment]
@bors-servo r+

Thanks!

**Pull request merged**
