### PR TITLE
Make .into_iter() work

### LINKED ISSUE #10: .into_iter() doesn't work
The following code:

```rust
extern crate smallvec;

fn main() {
    let mut vec: smallvec::SmallVec<[u8; 8]> = smallvec::SmallVec::new();

    vec.push(5);

    println!("{:?}", vec.len());

    for num in vec.into_iter() {
        println!("{:?}", num);
    }
}
```

Prints:
```
1
```

Expected:
```
1
5
```

This is probably because `into_iter()` sets the length to `0`, and then only calls `iter_mut()`, therefore getting an iterator of length `0`.

### PR DESCRIPTION
**Pull request by tomaka**
Fix #10

### CODE REVIEW

**Comment by SimonSapin** [comment]
Thanks!

**Comment by tomaka** [comment]
Could this change be published on crates.io please?

**Comment by SimonSapin** [comment]
Done.

**Comment by tomaka** [comment]
Thanks!

**Pull request merged**
