### PR TITLE
Implemented DrainFilter

### PR DESCRIPTION
**Pull request by L0uisc**
Provides an implementation for DrainFilter (issue #281).

### CODE REVIEW

**Comment by L0uisc** [comment]
I've reviewed this now, and I'm now doubly sure it does what it should. Review by another human would be appreciated, but from my side, I think it's good to go.

**Comment by L0uisc** [comment]
Anything I still need to do with this?

**Comment by mbrubeck** [comment]
Sorry for the delay.  I'll try to review this soon (if another maintainer doesn't get to it first).

**Comment by L0uisc** [comment]
No worries! I just wanted to confirm if I still need to do something before the review process can start.

**Comment by mbrubeck** [comment]
@bors-servo r+

Sorry for the wait!

**Pull request merged**
