### PR TITLE
Use min_const_generics

### PR DESCRIPTION
**Pull request by c410-f3r**

### CODE REVIEW

**Comment by jdm** [comment]
```
error[E0658]: const generics are unstable

    --> src/lib.rs:1910:22

     |

1910 | unsafe impl<T, const N: usize> Array for [T; N] {

     |                      ^

     |

     = note: see issue #44580 <https://github.com/rust-lang/rust/issues/44580> for more information

     = help: add `#![feature(const_generics)]` to the crate attributes to enable
```

**Comment by jdm** [comment]
That failure occurs as part of [this command](https://github.com/servo/rust-smallvec/blob/f7e01ef2684c046d31a467b6802f478e88e95677/scripts/run_miri.sh#L21).

**Comment by mbrubeck** [comment]
We'll need to wait for a newer nightly that includes miri.

**Pull request merged**
