### PR TITLE
bump heapsize to 0.4.0

### PR DESCRIPTION
**Pull request by rphmeier**
This change is [Reviewable](https://reviewable.io/reviews/servo/rust-smallvec/50)

### CODE REVIEW

**Comment by rphmeier** [comment]
A push to crates.io when this is merged would be wonderful. It's one of the pre-reqs for bumping heapsize and fixing https://github.com/paritytech/parity/issues/5667

**Comment by jdm** [comment]
Could you update this crate's version number to 0.4.0?

**Comment by rphmeier** [comment]
Sure, just pushed.

**Comment by jdm** [comment]
Published!

**Comment by rphmeier** [comment]
Cheers, thanks for the quick response on this one :)

**Pull request merged**
